---
- name: Deploy VProfile Application on Amazon Linux / RHEL
  hosts: tomcatservers
  become: yes
  gather_facts: true

  tasks:
    - name: Install Java 1.8 OpenJDK
      yum:
        name: java-1.8.0-openjdk
        state: present

    - name: Install Tomcat
      amazon-linux-extras:
         name: tomcat9
         state: enabled

    - name: Start and enable Tomcat
      service:
        name: tomcat9
        state: started
        enabled: yes

    - name: Download latest VProfile.war file
      get_url:
        url: "http://{{ nexusip }}:8081/nexus/content/repositories/VProfile-repo/{{ groupid }}/{{ time }}/{{ build }}/{{ vprofile_version }}"
        dest: "/tmp/{{ vprofile_version }}"
        mode: '0755'

    - name: Stop Tomcat before deployment
      service:
        name: tomcat
        state: stopped

    - name: Remove existing VProfile
      file:
        path: /var/lib/tomcat/webapps/VProfile
        state: absent

    - name: Deploy WAR to Tomcat
      copy:
        src: "/tmp/{{ vprofile_version }}"
        dest: "/var/lib/tomcat/webapps/"
        mode: '0755'

    - name: Start Tomcat service
      service:
        name: tomcat
        state: started

    - name: Wait for WAR to deploy
      wait_for:
        path: "/var/lib/tomcat/webapps/{{ time }}-{{ build }}"
        timeout: 60

    - name: Link deployed WAR to /VProfile
      file:
        src: "/var/lib/tomcat/webapps/{{ time }}-{{ build }}"
        dest: "/var/lib/tomcat/webapps/VProfile"
        state: link

    - name: Stop iptables firewall
      service:
        name: iptables
        state: stopped
        enabled: no
        ignore_errors: yes
