---
- hosts: tomcatservers
  become: yes
  gather_facts: yes   # Enable this for OS checks and apt usage

  tasks:

  - name: Install Java 8 (OpenJDK) on Ubuntu
    apt:
      name: openjdk-8-jdk
      state: present
      update_cache: yes

  - name: Install Tomcat 9 on Ubuntu
    apt:
      name: tomcat9
      state: present
      update_cache: yes

  - name: Download latest VProfile.war file
    get_url:
      url: "http://{{nexusip}}:8081/nexus/content/repositories/VProfile-repo/{{groupid}}/{{time}}/{{build}}/{{vprofile_version}}"
      dest: /tmp/
      mode: '0755'

  - name: Stop Tomcat service
    service:
      name: tomcat9
      state: stopped

  - name: Copy artifact to Tomcat webapps folder
    copy:
      src: "/tmp/{{vprofile_version}}"
      dest: /var/lib/tomcat9/webapps/
      mode: '0644'

  - name: Delete existing VProfile symlink (if any)
    file:
      path: /var/lib/tomcat9/webapps/VProfile
      state: absent

  - name: Start Tomcat service
    service:
      name: tomcat9
      state: started

  - name: Wait for the app to be deployed
    wait_for:
      path: "/var/lib/tomcat9/webapps/{{time}}-{{build}}"
      timeout: 60

  - name: Create symbolic link to latest VProfile version
    file:
      src: "/var/lib/tomcat9/webapps/{{time}}-{{build}}"
      dest: "/var/lib/tomcat9/webapps/VProfile"
      state: link

  - name: Stop ufw (Ubuntu firewall) instead of iptables
    service:
      name: ufw
      state: stopped
      enabled: no
