---
- hosts: tomcatservers
  become: yes
  gather_facts: yes

  vars:
    tomcat_service_name: tomcat8
    tomcat_webapps_dir: /var/lib/tomcat8/webapps

  tasks:

    - name: Install Java 1.8 OpenJDK
      yum:
        name: java-1.8.0-openjdk
        state: present

    - name: Enable tomcat8 from amazon-linux-extras
      amazon-linux-extras:
        name: tomcat8
        state: enabled

    - name: Install tomcat8
      yum:
        name: tomcat8
        state: present

    - name: Ensure tomcat service is started and enabled
      service:
        name: "{{ tomcat_service_name }}"
        state: started
        enabled: yes

    - name: Download latest VProfile.war file
      get_url:
        url: "http://{{ nexusip }}:8081/nexus/content/repositories/VProfile-repo/{{ groupid }}/{{ time }}/{{ build }}/{{ vprofile_version }}"
        dest: "/tmp/{{ vprofile_version }}"
        mode: '0644'

    - name: Stop tomcat service before deployment
      service:
        name: "{{ tomcat_service_name }}"
        state: stopped

    - name: Remove existing deployed VProfile app folder or symlink
      file:
        path: "{{ tomcat_webapps_dir }}/VProfile"
        state: absent

    - name: Copy WAR file to tomcat webapps directory
      copy:
        src: "/tmp/{{ vprofile_version }}"
        dest: "{{ tomcat_webapps_dir }}/VProfile.war"
        mode: '0644'

    - name: Start tomcat service after deployment
      service:
        name: "{{ tomcat_service_name }}"
        state: started

    - name: Wait for tomcat to deploy WAR (check folder creation)
      wait_for:
        path: "{{ tomcat_webapps_dir }}/VProfile"
        timeout: 120
        state: directory

    - name: Optionally create symlink if you want versioned folder linked as VProfile (uncomment if needed)
      file:
        src: "{{ tomcat_webapps_dir }}/{{ time }}-{{ build }}"
        dest: "{{ tomcat_webapps_dir }}/VProfile"
        state: link

    # Add other tasks if needed, e.g. stopping firewall, configuring SELinux, etc.
